version: 2
notify:
  webhooks:
    - url: https://circledisc-clarity.herokuapp.com/webhook/circle

jobs:
  build_git_linux:
    machine: 
      image: ubuntu-1604:201903-01 
    environment:
      # We're allowing people to download nightlies through CircleCI's artifacts
      # so we're gonna be packaging it as close as possible to the released versions.
      VSCODE_VERSION: '1.38.1'
      VERSION: .git-nightly
      MINIFY: 'true'
      PACKAGE: 'true'
      TARGET: linux
    steps:
      - checkout
      - run:
         name: "Run CI Steps"
         command: ./scripts/ci.bash
      - store_artifacts:
          path: ./release/

  build_git_alpine:
    machine: 
      image: ubuntu-1604:201903-01 
    environment:
      VSCODE_VERSION: '1.38.1'
      VERSION: .git-nightly
      MINIFY: 'true'
      PACKAGE: 'true'
      TARGET: alpine
    steps:
      - checkout
      - run:
         name: "Run CI Steps"
         command: ./scripts/ci.bash
      - store_artifacts:
          path: ./release/

  build_git_macos:
    macos:
      xcode: 11.0.0 
    environment:
      VSCODE_VERSION: '1.38.1'
      VERSION: .git-nightly
      MINIFY: 'true'
      PACKAGE: 'true'
      TARGET: ''
    steps:
      - checkout
      - run:
         name: "Run CI Steps"
         command: ./scripts/ci.bash
      - store_artifacts:
          path: ./release/

workflows:
  version: 2
  untagged-build:
    jobs:
      - build_git_linux
      - build_git_alpine
      - build_git_macos

  tagged-build:
    jobs:
      - build_release_linux:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9].[0-9]{4}-vsc[0-9].[0-9]{2}.[0-9]/

      - build_release_alpine:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9].[0-9]{4}-vsc[0-9].[0-9]{2}.[0-9]/
      - build_release_macos:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9].[0-9]{4}-vsc[0-9].[0-9]{2}.[0-9]/
