version: 2
notify:
  webhooks:
    - url: https://circledisc-clarity.herokuapp.com/webhook/circle

jobs:
  build_git_linux:
    machine: 
      image: ubuntu-1604:201903-01 
    env:
      # We're allowing people to download nightlies through CircleCI's artifacts
      # so we're gonna be packaging it as close as possible to the released versions.
      VSCODE_VERSION: 1.38.1
      VERSION: .git-nightly
      MINIFY: true
      PACKAGE: true
      TARGET: linux
      PLATFORM: $(if [ -z $TARGET ]; then echo "darwin"; fi)
    steps:
      - checkout
      - run:
         name: "Run CI Steps"
         command: ./scripts/ci.bash
      - store_artifacts:
          path: ./release/

  build_git_alpine:
    machine: 
      image: ubuntu-1604:201903-01 
    env:
      VSCODE_VERSION: 1.38.1
      VERSION: .git-nightly
      MINIFY: true
      PACKAGE: true
      TARGET: alpine
      PLATFORM: $(if [ -z $TARGET ]; then echo "darwin"; fi)
    steps:
      - checkout
      - run:
         name: "Run CI Steps"
         command: ./scripts/ci.bash
      - store_artifacts:
          path: ./release/

  build_git_macos:
    macos:
      xcode: 11.0.0 
    env:
      VSCODE_VERSION: 1.38.1
      VERSION: .git-nightly
      MINIFY: true
      PACKAGE: true
      TARGET: ''
      PLATFORM: $(if [ -z $TARGET ]; then echo "darwin"; fi)
    steps:
      - checkout
      - run:
         name: "Run CI Steps"
         command: ./scripts/ci.bash
      - store_artifacts:
          path: ./release/