name: Build
on: [push, pull_request]
jobs:
  build_amd64:
    name: Build (AMD64 - CentOS 7 Target)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build code-server Binary
        run: yarn && bash ./scripts/ci.bash  
        env:
           VERSION: master
           TARGET: 'linux'
           VSCODE_VERSION: '1.38.1'
           MINIFY: 'true' 
           PACKAGE: 'true'
  build_amd64_alpine:
    name: Build (AMD64 - Alpine Target)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build code-server Binary
        run: yarn && bash ./scripts/ci.bash  
        env:
           VERSION: master
           TARGET: 'alpine'
           VSCODE_VERSION: '1.38.1'
           MINIFY: 'true' 
           PACKAGE: 'true'
  build_macos:
    name: Build (macOS Target)
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1

      - name: Workaround outdated Node in CI
        run: brew uninstall node@6 && brew install node@12

      - name: Build code-server Binary
        run: yarn && bash ./scripts/ci.bash  
        env:
           VERSION: master
           TARGET: ''
           VSCODE_VERSION: '1.38.1'
           MINIFY: 'true' 
           PACKAGE: 'true'