name: Build
on:
  push:
    tags:
      - '*'
jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build code-server Binary
        run: scripts/ci.bash  
        env:
           MAJOR_VERSION: '2'
           VERSION: '${MAJOR_VERSION}.${GITHUB_SHA}'
           VSCODE_VERSION: '1.38.1'
           MINIFY: 'true' 
           PACKAGE: 'true'
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release/*.tar.gz,release/*.zip"
        bodyFile: "CHANGELOG.md"
        token: ${{ secrets.GITHUB_TOKEN }}