name: Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    strategy:
       matrix:
         platform: [ubuntu-latest, macos-latest]
         linux-platforms: ['linux', 'alpine']
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
           node-version: '10.x'

      - name: Build code-server binary (Linux)
        run: bash ./scripts/ci.bash    
        env:
           MAJOR_VERSION: '2'
           TARGET: ${{ matrix.linux-platforms }}
           VERSION: '${MAJOR_VERSION}.${GITHUB_SHA}'
           VSCODE_VERSION: '1.38.1'
           MINIFY: 'true' 
           PACKAGE: 'true'

      - name: Build code-server binary (macOS)
        if: contains( ${{ matrix.platform }} , 'macos-latest')
        run: bash ./scripts/ci.bash    
        env:
           MAJOR_VERSION: '2'
           VERSION: '${MAJOR_VERSION}.${GITHUB_SHA}'
           VSCODE_VERSION: '1.38.1'
           MINIFY: 'true' 
           PACKAGE: 'true'